# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reddit.proto',
  package='example',
  syntax='proto2',
  serialized_pb=_b('\n\x0creddit.proto\x12\x07\x65xample\"\x83\x01\n\x0cRedditRecord\x12\r\n\x05title\x18\x01 \x02(\t\x12\r\n\x05score\x18\x02 \x02(\x03\x12\n\n\x02id\x18\x03 \x02(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x11\n\tcomms_num\x18\x05 \x01(\x03\x12\x0f\n\x07\x63reated\x18\x06 \x01(\x02\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x12\n\n\x02ts\x18\x08 \x01(\t\"2\n\tReditData\x12%\n\x06record\x18\x01 \x03(\x0b\x32\x15.example.RedditRecord')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REDDITRECORD = _descriptor.Descriptor(
  name='RedditRecord',
  full_name='example.RedditRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='example.RedditRecord.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='example.RedditRecord.score', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='example.RedditRecord.id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='example.RedditRecord.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comms_num', full_name='example.RedditRecord.comms_num', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created', full_name='example.RedditRecord.created', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='example.RedditRecord.body', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ts', full_name='example.RedditRecord.ts', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=157,
)


_REDITDATA = _descriptor.Descriptor(
  name='ReditData',
  full_name='example.ReditData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='example.ReditData.record', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=209,
)

_REDITDATA.fields_by_name['record'].message_type = _REDDITRECORD
DESCRIPTOR.message_types_by_name['RedditRecord'] = _REDDITRECORD
DESCRIPTOR.message_types_by_name['ReditData'] = _REDITDATA

RedditRecord = _reflection.GeneratedProtocolMessageType('RedditRecord', (_message.Message,), dict(
  DESCRIPTOR = _REDDITRECORD,
  __module__ = 'reddit_pb2'
  # @@protoc_insertion_point(class_scope:example.RedditRecord)
  ))
_sym_db.RegisterMessage(RedditRecord)

ReditData = _reflection.GeneratedProtocolMessageType('ReditData', (_message.Message,), dict(
  DESCRIPTOR = _REDITDATA,
  __module__ = 'reddit_pb2'
  # @@protoc_insertion_point(class_scope:example.ReditData)
  ))
_sym_db.RegisterMessage(ReditData)


# @@protoc_insertion_point(module_scope)
